all: InsertionSort

debug: InsertionSort.cpp InsertionSort.h
	g++ -g -o InsertionSort InsertionSort.cpp

InsertionSort: InsertionSort.cpp InsertionSort.h
	g++ -o InsertionSort InsertionSort.cpp

ShellSort: ShellSort.cpp ShellSort.h
	g++ -o ShellSort ShellSort.cpp

clean:
	rm *.exe