all: InsertionSort

debug: InsertionSort.cpp InsertionSort.h
	g++ -g -o InsertionSort InsertionSort.cpp

InsertionSort: InsertionSort.cpp InsertionSort.h
	g++ -o InsertionSort InsertionSort.cpp

clean:
	rm *.exe