BottomUpMergesort: BottomUpMergesort.o BottomUp.o

		g++ -o BottomUpMergesort BottomUpMergesort.o BottomUp.o


BottomUpMergesort.o: BottomUpMergesort.cpp
		
		g++ -c BottomUpMergesort.cpp


BottomUp.o: BottomUp.cpp
		
		g++ -c BottomUp.cpp


clean: 
	
		rm BottomUpMergesort *.o

